# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_auto_20170411_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='rss_etag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
