# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_feed_rss_etag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeditem',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='feed',
            name='telegram_notifications',
            field=models.BooleanField(default=False, help_text='Send notifications about new feed items to telegram'),
        ),
    ]
